container:
  image: node:latest

check_task:
  env:
    CODECOV_TOKEN: 958b2c5e-7ea8-4b83-af81-c0e4b6761857

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: yarn install

  lint_script: yarn run lint

  test_script: yarn run test && bash <(curl -s https://codecov.io/bash)

  build_script: yarn run build
