container:
  image: node:16

check_task:
  env:
    CODECOV_TOKEN: 958b2c5e-7ea8-4b83-af81-c0e4b6761857

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install

  lint_script: npm run lint

  test_script: npm run test && bash <(curl -s https://codecov.io/bash)

  build_script: npm run build
