export { default as print } from "./print/print";
export { default as getPrinters } from "./get-printers/get-printers";
export { default as getDefaultPrinter } from "./get-default-printer/get-default-printer";
export { PrintOptions } from "./print/print";

export type Printer = Partial<{
  deviceId: string;
  name: string;
  status: string;
  caption: string;
  description: string;
  installDate: string;
  availability: string;
  configManagerErrorCode: string;
  configManagerUserConfig: string;
  creationClassName: string;
  errorCleared: string;
  errorDescription: string;
  lastErrorCode: string;
  pNPDeviceId: string;
  powerManagementCapabilities: string[];
  powerManagementSupported: string;
  statusInfo: string;
  systemCreationClassName: string;
  systemName: string;
  availableJobSheets: string[];
  capabilities: string[];
  capabilityDescriptions: string[];
  charSetsSupported: string[];
  currentCapabilities: string[];
  currentCharSet: string;
  currentLanguage: string;
  currentMimeType: string;
  currentNaturalLanguage: string;
  currentPaperType: string;
  defaultCapabilities: string[];
  defaultCopies: string;
  defaultLanguage: string;
  defaultMimeType: string;
  defaultNumberUp: string;
  defaultPaperType: string;
  detectedErrorState: string;
  errorInformation: string[];
  horizontalResolution: string;
  jobCountSinceLastReset: string;
  languagesSupported: string[];
  markingTechnology: string;
  maxCopies: string;
  maxNumberUp: string;
  maxSizeSupported: string;
  mimeTypesSupported: string[];
  naturalLanguagesSupported: string[];
  paperSizesSupported: string[];
  paperTypesAvailable: string[];
  printerStatus: string;
  timeOfLastReset: string;
  verticalResolution: string;
  attributes: string;
  averagePagesPerMinute: string;
  comment: string;
  default: string;
  defaultPriority: string;
  direct: string;
  doCompleteFirst: string;
  driverName: string;
  enableBIDI: string;
  enableDevQueryPrint: string;
  extendedDetectedErrorState: string;
  extendedPrinterStatus: string;
  hidden: string;
  keepPrintedJobs: string;
  local: string;
  location: string;
  network: string;
  parameters: string;
  portName: string;
  printerPaperNames: string[];
  printerState: string;
  printJobDataType: string;
  printProcessor: string;
  priority: string;
  published: string;
  queued: string;
  rawOnly: string;
  separatorFile: string;
  serverName: string;
  shared: string;
  shareName: string;
  spoolEnabled: string;
  startTime: string;
  untilTime: string;
  workOffline: string;
}>;

export const defaultProperties: (keyof Printer)[] = ["deviceId", "name"];
